### ISSUE TITLE
1.0.5 release date

### ISSUE THREAD

**Issue by matt-shaw** [stevespringett/dependency-check-sonar-plugin#10]
Hi Steve,

Would it be possible to produce a release with the fix for issue 5.  I can only use official releases and issue 5 is the last issue that prevents us using this plugin.

Regards

Matt

**Comment by rigoford** [comment]
Hi Steve,

I'm also interested in a new release (1.0.2 I guess) that contains the changed behaviour for missing dependency-check reports.

Very handy plugin by the way.

Thanks

Martin

**Comment by stevespringett** [comment]
1.0.2 Released

**Comment by rigoford** [comment]
Excellent! Many thanks.
