### ISSUE TITLE
dependency-check="none" or Object not plugin in XML

### ISSUE THREAD

**Issue by Nitinkhanna1** [stevespringett/dependency-check-sonar-plugin#100]

**Comment by Nitinkhanna1** [comment]
Some please suggest 
<bean id="c" class="Project"  dependency-check="none">
dependency-check not plugin cvc-complex type  attribute not allowed

**Comment by Nitinkhanna1** [comment]
Some one  please suggest

dependency-check not plugin cvc-complex type attribute not allowed

**Comment by Reamer** [comment]
Doesn't understand you. Can you provide a log message?
