### ISSUE TITLE
How to cache CVE updates?

### ISSUE THREAD

**Issue by yegorski** [stevespringett/dependency-check-sonar-plugin#104]
Is there a way to cache the updates?

Asking because I'm using `dependency-check` in a docker image, and on every run it spends a good while pulling updates i.e.

```
[INFO] Processing Complete for NVD CVE - 2003  (14664 ms)
```

**Comment by stevespringett** [comment]
You could:
* Use a centralized database
* Use a mirror of the NVD
* Use a shared data directory

Any of these approaches would dramatically speed up (or eliminate) the constant downloading of NVD data feeds.

**Comment by yegorski** [comment]
Thanks for the lighting-fast reply.

I would still need to run a sample scan to generate the database locally (I don't have a centralized one), then cache the updates in a shared directory.

Follow up: is there such command I can run, or should I perform a scan of dummy project (which will start up the update process)?

**Comment by stevespringett** [comment]
If you want to use a shared data directory then use the `updateonly` option to keep the data directory updated on a daily basis, and whenever you scan ensure you disable the `autoupdate` feature. You can also specify the location to the data directory. Sorry, I don't have the exact syntax for Docker, but these are all features that should be exposed.

You can also look at https://jeremylong.github.io/DependencyCheck/data/mirrornvd.html for general info on how to mirror the NVD which can reduce the likelihood of getting 429's from the NVD on a lot of usage.

**Comment by yegorski** [comment]
Great, I'll check it out! Will post back if I settle on a caching approach.

**Comment by yegorski** [comment]
So what I've done is ran a sample report of a NodeJS project inside a docker container:

```
. . .
npm install
nyc npm test
eslint -f json -o eslint-report.json .
. . .
dependency-checker --format HTML --scan src --out . --project "My App"
```

This cached the `data/` dir with the following:

```
ls -larth dependency-check/data/
total 441364
-rw-r--r--    1 root     root       47.7K Feb  4 16:05 jsrepository.json
drwxr-xr-x    7 root     root         408 Feb  4 16:27 ..
-rw-r--r--    1 root     root      431.0M Feb  4 18:45 dc.h2.db
drwxr-xr-x    2 root     root         136 Feb  4 18:45 .
```

I'm still seeing the CVE updates being performed but they only take 2 minutes:

```
[INFO] Check for updates complete (124044 ms)
```

This is an acceptable time for me. I remember the updates taking much longer before, so this caching seems to be working.

**Comment by yegorski** [comment]
The only thing now is that the Dependency-Check tab in SonarQube thinks that my app is vulnerability-free (which is ridiculous), so I need to figure out how to show the output in the UI 🤣
