### ISSUE TITLE
Vulnerabilities not displayed on Sonarqube

### ISSUE THREAD

**Issue by BruGit** [stevespringett/dependency-check-sonar-plugin#105]
Good evening,
I need your help because, see the attachment, the plugin seems works (the reports are correctly generated) but in Sonarqube like measures, just the dependencies are displayed.
In reports, vulnerabilities are present but as you can see from the first screen on Sonarqube are all = 0.

![1](https://user-images.githubusercontent.com/47569258/52649773-38feef80-2ee9-11e9-8eb4-bacf87a7ebc3.PNG)

![2](https://user-images.githubusercontent.com/47569258/52650205-14574780-2eea-11e9-94e0-52a4e699555c.PNG)

Sonarqube version: 7.6 - Dependency Check Plugin: 1.1.1
Please let me know if you need other.

**Comment by Reamer** [comment]
Please check use a newer version https://github.com/stevespringett/dependency-check-sonar-plugin/releases

**Comment by BruGit** [comment]
It works, many thanks Reamer!
