### ISSUE TITLE
Warning on missing HTML report refers incorrect property

### ISSUE THREAD

**Issue by wkoot** [stevespringett/dependency-check-sonar-plugin#108]
The warning listed below is produced when the xml report file is found but the html report file is not.
The property mentioned in logging should be `htmlReportPath`, but it would also be desirable to lower log to INFO when the xml report is there.

```WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.html```

**Comment by Reamer** [comment]
Which version of the plugin do you use?
In this part of code you can see that we are already on INFO Logleve
https://github.com/stevespringett/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java#L233

**Comment by wkoot** [comment]
Oh, I have 1.1.0 installed via sonar marketplace - it does not list a newer one available.
Probably due to SonarQube version 6.X? I'll try to upgrade, thanks
