### ISSUE TITLE
Download link is unavailable

### ISSUE THREAD

**Issue by ep4sh** [stevespringett/dependency-check-sonar-plugin#109]
Good day, by clicking "Download" - get 404 Error.

![image](https://user-images.githubusercontent.com/19505042/53804090-9a016c80-3f57-11e9-9953-a11267acfb2b.png)

Link location:
https://bintray.com/stevespringett/owasp/dependency-check-sonar/_latestVersion

**Comment by Reamer** [comment]
Thanks for issue.
Just removed Link. https://github.com/stevespringett/dependency-check-sonar-plugin/commit/608a43a9ac2c1df3c38b187edf7873af9fbcc715
Please use https://github.com/stevespringett/dependency-check-sonar-plugin/releases
