### ISSUE TITLE
Not able to download jar sonar-dependency-check-1.0.3

### ISSUE THREAD

**Issue by ricky001** [stevespringett/dependency-check-sonar-plugin#111]
Not able to download the Not able to download jar sonar-dependency-check-1.0.3 from 
https://github.com/stevespringett/dependency-check-sonar-plugin/releases

**Comment by Reamer** [comment]
Does this link work for you? https://github.com/stevespringett/dependency-check-sonar-plugin/releases/download/sonar-dependency-check-1.0.3/sonar-dependency-check-plugin-1.0.3.jar

**Comment by ricky001** [comment]
No the error "This site can’t be reached"

**Comment by Reamer** [comment]
I can download this jar. Maybe a GitHub or a local firewall issue.

**Comment by ricky001** [comment]
is it there on maven

**Comment by Reamer** [comment]
No it's not part of any maven repository.

**Comment by Reamer** [comment]
If the provided link doesn't work. You can build this plugin on your own. I recommend to checkout a specific git tag. 
Build with `mvn clean package`. JAR is placed in `sonar-dependency-check-plugin/target/`
