### ISSUE TITLE
Issue with dependency check plugin for Sonarqube

### ISSUE THREAD

**Issue by sbabburu** [stevespringett/dependency-check-sonar-plugin#112]
Hello,
we are using sonar-dependency-check-plugin-1.1.0.jar in our sonaqube server(version 6.7.2) and it was working fine but suddenly we are getting the below error on our builds, can someone please advise. Thank you.

 
[ERROR] .NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'mono' executable could not be found on the path; either disable the Assembly Analyzer or configure the path mono. On some systems mono-runtime and mono-devel need to be installed.

**Comment by Reamer** [comment]
Hi @sbabburu,
I think your error message is not related with this module. Please provide a Stacktrace or debug logs.

**Comment by Reamer** [comment]
Hi @sbabburu,
I saw your screenshot in https://github.com/stevespringett/dependency-check-sonar-plugin/issues/23#issuecomment-475724935
The error is not related with this plugin. Please checkout the project which generates the report files. https://github.com/jeremylong/DependencyCheck
