### ISSUE TITLE
"Can not process Dependency-Check report. Not supported during sensor phase"

### ISSUE THREAD

**Issue by RaphaelDG** [stevespringett/dependency-check-sonar-plugin#12]
Hi,
First I would like to say thanks you for your work.
I'm a beginer with Maven and Maven plugins, my office ask me to work on your Dependency-Check plugin, and i'm on it since you publish the 1.3.1 version.
I use the 1.3.3version of the Dependency-Check Maven plugin and the last version of the SonarQube plugin with SonarQube 5.2.

But on some projects i've got this error that I don't understand:
<code>
[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar (default-cli) on project maven-single-module: Can not process Dependency-Check report. Not supported during sensor phase -> [Help 1]
</code>
I want to precise that the plugin Dependency-Check for SonarQube 5.2 allready worked on projects that didn't have any vulnerabilities.

I think that my pom is correctly configured (it's your mavenproject sample with personal edit), and SonarQube got the XML plugin:
<code>http://pastebin.fr/44123</code>

So I have this error after runing the commande sonar:sonar. 
The Dependency-check-report.xml exist.

Did you have any ideas to help me?

Thanks in advance.
RaphaelDLG.

<b> EDIT:
For me the  plugin only work on project that didn't have any vulnerability.
I did a MavenProject with no vunlerability: plugin find the report that say that there is no vulnerability.
But when I tried to put volontary some vulnerable dependency on this project:I have the same error that i quoted above. </b>

**Comment by stevespringett** [comment]
I noticed you're running Sonarqube analysis using sonar:sonar via the Maven plugin. I've had problems with the SonarQube Maven plugin in the past. 

I recommend executing the Dependency-Check and SonarQube analysis like so:
     
     mvn clean dependency-check:check
     sonar-runner

And if you're using Jenkins, just use the Jenkins SonarQube plugin to kick off the analysis. Works great.

**Comment by RaphaelDG** [comment]
Thanks you for responding quickly.
I tried with sonar-runner (with all corect sonar properties) but still the same error.
Here there is a screenshot with all informations:
http://postimg.org/image/966h4aycx/

I justblancked my username but the path is correct, i'm sure that the plugin find the dependency report.

Thanks,
RaphaelDG

**Comment by stevespringett** [comment]
I just committed a change which no longer requires dependency-check-report.xml to appear in the sonar.source path. Can you test with the current checked in code and let me know if you're still having issues?

**Comment by stevespringett** [comment]
I just noticed that this is a duplicate of #11 which has already been resolved.
