### ISSUE TITLE
Windows Paths not working with Jenkins Slave

### ISSUE THREAD

**Issue by robertredd** [stevespringett/dependency-check-sonar-plugin#14]
I just installed the sonar plugin and I got the plugin to work with my Jenkins installation, but I had to hard-code the path like this:
sonar.dependencyCheck.reportPath=C:/jenkins/workspace/ah-defect-reporting-service-dev/dependency-check-report.xml

I also had to use forward-slashes or it wouldn't work (This is a Windows Jenkins Slave).

The real issue is I want to use the ${WORKSPACE}/dependency-check-report.xml
But, if I use that I get the following output:
INFO: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: C:jenkinsworkspaceah-defect-reporting-service-devdependency-check-report.xml

The slashes are all removed.

If I just use the path with no hard-coded path it can't find it per below example even though the file is in the root of the workspace.

Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: dependency-check-report.xml

**Comment by stevespringett** [comment]
@robertredd I cannot reproduce using the following components:

- Jenkins 1.609.1
- SonarQube Jenkins Plugin v2.3
- SonarQube 5.2
- Dependency-Check SonarQube Plugin v1.0.3

In my environment, I'm running Jenkins master node and SonarQube on OSX, and running a Jenkins slave node and corresponding job on a Windows 10 machine.

The analysis properties in the SonarQube Jenkins Plugin are configured as follows:

sonar.projectKey=my-project-key
sonar.projectName=My Project Name
sonar.projectVersion=1.0.0-SNAPSHOT
sonar.sources=./src
sonar.dependencyCheck.reportPath=./reports/dependency-check-report.xml

With this configuration, the Windows 10 slave node running the job correctly finds the dependency-check report, parses it, and populates SonarQube with the results for the given project key.

**Comment by stevespringett** [comment]
Also tested with SonarQube 5.4. Works as expected

**Comment by robertredd** [comment]
I see what is happening.  I do a checkout into a "source" subdir within the workspace.  So, relative to that is up a directory to the root of the workspace where the report is located.  I changed it the following and now it's working fine.  Thanks for looking into it, your research showed that it must be something I was missing.

sonar.dependencyCheck.reportPath=../dependency-check-report.xml
