### ISSUE TITLE
Integrate this plugin in official SonarQube plugin repository?

### ISSUE THREAD

**Issue by victornoel** [stevespringett/dependency-check-sonar-plugin#16]
Hi,

Do you plan on integrating dependency-check-sonar-plugin in the official SonarQube plugin repository so that it can be installed automatically from the UI?

**Comment by giacgbj** [comment]
+1

**Comment by stevespringett** [comment]
I would like to and have actually attempted this process twice. SonarSource is very political and process orientated and not well suited for open source plugin development. If and when SonarSource makes the process of adding plugins simpler (like it is for Jenkins), I will reconsider adding it to the official plugin repo. 

As of now, the Dependency-Check plugin is listed here: http://docs.sonarqube.org/display/PLUG/Other+Plugins with all the other plugins not available in the update center.

If and when SonarSource simplifies their processes, feel free to reopen this ticket.
