### ISSUE TITLE
Issue displaying report

### ISSUE THREAD

**Issue by radmilabord** [stevespringett/dependency-check-sonar-plugin#17]
I'm having issues with displaying vulnerabilities on SonarQube. Here are the steps I followed:

1. Installed dependency-check-sonar-plugin version 1.0.3 on SonarQube.

2. Configured dashboard to include Vulnerabilities widjet.

3. Generated dependency report using: mvn org.owasp:dependency-check-maven:1.3.6:check -Dformat=XML.

4. Report was placed into [project]/target/dependency-check-report.xml

5. Ran sonar task: org.codehaus.mojo:sonar-maven-plugin:2.3:sonar Task completed successfully but I don't see data in the Vulnerabilities widjet. Anyone has idea what could prevent plugin from seeing report?

Thanks in advance! Rada

**Comment by stevespringett** [comment]
Did you take a look at the [examples](https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples/single-module-maven)?

You may need to add:
`<sonar.dependencyCheck.reportPath>${project.build.directory}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>`

**Comment by radmilabord** [comment]
Steve, thank you so much!!! your input helped to tie report and sonar together and I'm seeing results!!!
I appreciate your help!!!
