### ISSUE TITLE
SonarLint and Neutral Quality Profile

### ISSUE THREAD

**Issue by apieraf** [stevespringett/dependency-check-sonar-plugin#18]
Hi, 

When I try to bind a project in eclipse with SonarLint, with a SonarQube project, eclipse shows me the next error
![image](https://cloud.githubusercontent.com/assets/6850090/16649125/a8f85f6e-4437-11e6-9a2e-5275a32a696a.png)

The profile neutral-neutral-13672 has only one rule **Using Components with Known Vulnerabilities**

I need fix that issue to work with eclipse, sonarlint and dependency-check

Thanks in advance

**Comment by stevespringett** [comment]
Dependency-Check SonarQube plugin is very specialized by providing visibility to one of the OWASP Top Ten issues, specially 'A9: Using Component with Known Vulnerabilities'. As such, there is only one rule.

I cannot simply create random rules to satisfy the requirement of some other plugin. I would recommend filling an issue with the Sonarlint team to support plugins containing only one rule.

**Comment by apieraf** [comment]
I think that is a problem of dependency check plugin, specifically the quality profile that creates the plugin, because when I uninstall the plugin, SonarLint works fine. Anyway I'll talk to the team SonarLint
