### ISSUE TITLE
Issue severity is critical instead of major

### ISSUE THREAD

**Issue by ArloL** [stevespringett/dependency-check-sonar-plugin#20]
First of all thanks for this plugin. I am really looking forward to using this for all our projects.

I am not sure whether this is just me doing something wrong but somehow the vulnerabilities are marked as critical instead of major as configured.

![issue](https://cloud.githubusercontent.com/assets/195367/16979009/35ca2126-4e5f-11e6-9a79-e44d6b660c55.PNG)

![rule](https://cloud.githubusercontent.com/assets/195367/16979017/3795fda4-4e5f-11e6-8cc3-d215fc8aac6c.PNG)

This is dependency-check-sonar-plugin 1.0.3 and SonarQube 5.6. Please let me know if I can provide you with more details or whether I should ask somewhere else.

Thanks :smile:

**Comment by stevespringett** [comment]
SonarQube doesn't have traditional security-specific security ratings, so the rating is hard coded to match the severity output from Dependency-Check which follows the recommendations from NIST.

CVSS Score >= 7.0 = Critical (High)
CVSS Score 4.0-6.9 = Major (Medium)
CVSS Score < 4.0 = Minor (Low)

What I did not want to do is have configurable severities in SonarQube, when the output from Dependency-Check and the Jenkins dashboard would display an entirely different rating.

Ideally, the severities could be broken down into Critical, High, Medium, and Low, however, Sonar doesn't allow this as the Severity class has hard coded items and cannot be extended.

**Comment by ArloL** [comment]
Thanks for the clarification. This makes a lot of sense and I will have to think about how to set it up taking this into consideration.

Just to give you an idea of what I was trying to achieve:

I am introducing the dependency-check-maven-plugin into our CI builds that also run a sonar check. We are using the [Build Breaker Plugin for SonarQube](https://github.com/SonarQubeCommunity/sonar-build-breaker). The Quality Gate is setup to trigger when there are critical issues. Since I was just trying to get an idea of what the state of our applications is I didn't want the Quality Gate to fail the builds. Just collect data and present it. Then I can update the problematic dependencies and following that let the builds fail for vulnerable dependencies.

What might be a possibility is to stop using the Build Breaker and just using SonarQube's notification system which as I understand is the preferred way anyway. I will have to talk this through with my colleagues though.

You can close the issue if you want. I will re-open if I have further questions.

Thanks!

**Comment by amandel** [comment]
Just as an idea, could you split it up in 3 different rules with different default severities? One for each CVSS range?
