### ISSUE TITLE
Feature Idea:  Make the SQ Severity assignment configurable

### ISSUE THREAD

**Issue by bdetchison** [stevespringett/dependency-check-sonar-plugin#22]
USE CASE:  I am investigating using this plugin and suites our needs with 1 exception.  For our enterprise we block builds if SQ quality gates have any new BLOCKER or new CRITICAL issues.  We would like to introduce this tool but we don't want to immediately be blocking builds because of the CRITICAL issues that get reported.  (though we would eventually want to turn this on)  It would be nice to have settings for which rating gets mapped to which SQ severity.  This would allow us to set our own thresholds.

This should be an easy enhancement and if I get time, I will submit a pull request.

Brandon

**Comment by ttsiebzehntt** [comment]
@bdetchison Had the exactly same requirement.

@stevespringett Submitted the PR #48 which adds this feature.
