### ISSUE TITLE
Will you update this plugin to use it with SonarQube 6.0+?

### ISSUE THREAD

**Issue by windson2ivan** [stevespringett/dependency-check-sonar-plugin#27]
@stevespringett Hi,i'm using this plugin,but it doesn't work with sonar 6.0. 
do you have any plan to update it?

**Comment by stevespringett** [comment]
There isn't a stable LTS release for 6.x yet nor is there a way to use the plugin in 6.0, 6.1, or 6.2. The dashboard (and widget support) was removed in 6.1 or 6.2 but its replacement won't be available until 6.3. So I'm expecting to support 6.3 or 6.4 when they are released as they will hopefully have the features necessary to support the plugin again.
