### ISSUE TITLE
Sonar Plugin reports failure when dependency-check.xml not present

### ISSUE THREAD

**Issue by mikechinaloy** [stevespringett/dependency-check-sonar-plugin#29]
Hi,

I have a large number of projects currently running in GoCD. For a small subset of them I am generating a dependency-check.xml and this plugin is reading them fine.

However, since installing the plugin the other projects (those not generating dependency-check.xml files) are now failing with:

`14:39:26.544 [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.6:sonar (default-cli) on project my-project2: Can not process Dependency-Check report. Dependency-Check report does not exist. -> [Help 1]`

Is this an issue with the sonar-maven-plugin I am using or is there a way to tell dependency-check to ignore projects that do not have the xml report present?

**Comment by mikechinaloy** [comment]
This only happens when using the 6.0 snapshot code in the PR https://github.com/stevespringett/dependency-check-sonar-plugin/pull/28.

**Comment by gtudan** [comment]
Hi @mikechinaloy,

Sorry your having an issue with the Snapshot. I also bumped into this issue today and will try to get it fixed asap.
