### ISSUE TITLE
Unable to view widget

### ISSUE THREAD

**Issue by gorgonsleddog** [stevespringett/dependency-check-sonar-plugin#30]
Good morning Steve,

I've started looking at your plugin and I started with your single-module example to get a better picture of what it will look like in SonarQube. In the README, there's an example of a widget, and I've been unable to create that. I followed the instructions on how to install it to SonarQube (I installed v1.0.3, SonarQube v6.2), and ran the dependency check on the sample. I see vulnerabilities show up in SonarQube, but no widget. Can you advise?

Best regards,
Scott

**Comment by stevespringett** [comment]
Refer to #21 . Support for SonarQube 6.x will likely come shortly after 6.3 is released. Closing as duplicate.
