### ISSUE TITLE
Latest release 1.1.0 not loading report in Sonarqube 6.5

### ISSUE THREAD

**Issue by justaman4326** [stevespringett/dependency-check-sonar-plugin#41]
Hello, I installed the plugin into my sonar instance however when I try to load the widget I get a blank page.  I have confirmed the report exists in my Jenkins workspace and am able to view it in Jenkins.  I believe everything is set up correctly; I left the defaults in all configs for Jenkins/Sonarqube project.  Looking at Chrome developer tools I see the following error when trying to load the widget:

"report.js:9 Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at report.js:9
    at <anonymous>"

Any thoughts?

**Comment by stevespringett** [comment]
The widget needs to be removed. SQ 6 no longer supports them. Clicking on 'Vulnerabilities' will display DC results and there will be a Dependency-Check option on the menu to display the DC HTML report (if you've specified it).

**Comment by NickHarvey2** [comment]
Is this error occurring when you try to view the embedded report on the custom page? Have you specified both parameters telling the plugin where to find the xml and html versions of the report? i.e.
`sonar.dependencyCheck.reportPath=${WORKSPACE}/dependency-check-report.xml`
`sonar.dependencyCheck.htmlReportPath=${WORKSPACE}/dependency-check-report.html`
and that both reports are being generated, by specifying `--format ALL` when the dependency check scan is run?

**Comment by justaman4326** [comment]
Thanks for the responses. I'll take a look at both suggestions when I get back to my station.

**Comment by justaman4326** [comment]
So I have confirmed that report path parameters are both set correctly to the Jenkins workspace root, and that the Jenkins job is generating both the xml and HTML reports.  Following @stevespringett instructions I clicked on 'Vulnerabilities' and I see 2 places where the 'OWASP-Dependency-Check' option is shown.

The first in the 'More' dropdown displays an empty page.  The second as shown in the 'Measures' tab has values of '0' for every category.

![image](https://user-images.githubusercontent.com/20275612/31742646-d910e4f8-b41d-11e7-85a5-68d2b2bd08c5.png)

![image](https://user-images.githubusercontent.com/20275612/31742670-eec76cc2-b41d-11e7-9ede-58f248695b98.png)

**Comment by NickHarvey2** [comment]
so it sounds like the report is getting generated, but for whatever reason is not getting found and picked up by the plugin.

when the file can't be found the plugin should log out a debug message "Analysis aborted due to missing report file". Can you check the Jenkins build logs for something like this?

**Comment by justaman4326** [comment]
@NickHarvey2 You were correct I did see that in the logs and it helped me realize the reportpath did not need the ${WORKSPACE} environment variable since I placed the sonar-project.properties file and generated reports all in the workspace root folder.  Once I removed the variable and re-ran the job all is well.  Thank you both for your assistance.
