### ISSUE TITLE
Consider suppression status when processing XML report

### ISSUE THREAD

**Issue by csetera** [stevespringett/dependency-check-sonar-plugin#42]
We have set up a suppressions file for the issues that we would like to mark as already dealt with in some way or another.  For the HTML report, that causes the issues to be filtered out.  However, the XML report includes that information within the data structures as suppression information.  Are there any plans to use this information to drive Sonar and/or filter out the vulnerabilities as they are being processed?

Unfortunately, I don't have any experience dealing with Sonar plugins, so I don't have a good way to help out in this regard.  I just know that my original hope/expectation had been that the issues we had already marked as suppressed would not show up in our reports.

**Comment by NickHarvey2** [comment]
@csetera @stevespringett  I'm currently focused on the TFS build plugin to run the dependency check, but once I finish that up, I could take a stab at this. All the bits to load and parse xml files are already in the plugin, it should just be a matter of specifying an additional file argument for the suppression file, building the relevant POJOs to deserialize suppression data into, then adding the issues conditionally, based on whether there is a suppression for them

**Comment by csetera** [comment]
That would be awesome.  I believe all of the information necessary is in the XML report.  In addition, it looked like the suppression information is modeled in the dependency checker core library as well.  I just don't really know how that would translate into Sonar.

**Comment by stevespringett** [comment]
What is the use case for having suppressed vulnerabilities inside SonarQube? At the moment, suppressed vulnerabilities are ignored since they are typically false positives.

In SQ, what you'll end up with is "fixed issues" for vulnerabilities that were previously unsuppressed, but are now suppressed. 
<img width="1445" alt="screen shot 2017-10-21 at 3 51 17 pm" src="https://user-images.githubusercontent.com/3878933/31855785-c0d94522-b677-11e7-903f-3e22c89bc3bb.png">

However, if your SQ project doesn't have historical data and you import a dependency-check report with suppressions, the suppressions will be ignored.

**Comment by csetera** [comment]
Maybe I did something wrong, but when I loaded our XML report (via mvn sonar:sonar) with suppressions in the file, they did not come through as fixed.  They came through as open and I had to manually fix them via the UI.  Is there something I may have done to make it behave that way?

**Comment by stevespringett** [comment]
Not sure. The screenshot above is from a clean SQ 6.5 install. I'm not sure if there's a SQ config option somewhere that would keep those issues around or not.

Your XML report should have the following structure:
```xml
<analysis ...>
    ...
    <dependencies>
        <dependency>
            ...
            <vulnerabilities>
                <suppressedVulnerability>
                </suppressedVulnerability>
            </vulnerabilities>
        </dependency>
    </dependencies>
</analysis>
```

As long as the XML report has this format and you have `<suppressedVulnerability>` in the XML, they will be ignored when posted to SQ. Currently, code does not exist in the SQ plugin that imports the `<suppressedVulnerability>` element.

**Comment by csetera** [comment]
I really don't know what I was seeing originally, but now it does appear to working the way you suggest.  I'm going to close this for now since it seems to be working.

**Comment by stevespringett** [comment]
Ok good, glad its working
