### ISSUE TITLE
Can't find the HTML report in SonarQube GUI

### ISSUE THREAD

**Issue by jfallot** [stevespringett/dependency-check-sonar-plugin#45]
Hello,

My issue is rather a question about the plugIn:

Aftyer specifying also the path to the dependency-check HTML report, where should that report presented in the SonarQube GUI?
I currently can't find it in SonarQube 6.7 after successfully running the analysis.

Also, I understand from the code that the plugIn is pushing all the HTML report as a metric in Sonar:
the size of my dependency-check Html reports is up to 50 MBytes.
By running the sonar analysis every day, am I going to fill my database with such huge metric?
Can I limit the history of that report metric to keep only the last one ?

Thank you,
JF

**Comment by NickHarvey2** [comment]
It is at the project level, under "More"

![image](https://user-images.githubusercontent.com/24573707/33279266-9f148524-d363-11e7-96d9-b7b3bae574a6.png)

On the second question, when defining a metric, there is the option to call setDeleteHistoricalData(true), but it seems to apply to all instances of the metric, not something that could be configured on a case by case basis. I'm not sure if there's really value to keeping historical reports, but setting this to true would make that impossible.

from the doc:
> Specifies whether measures from the past can be automatically deleted to minimize database volume. 
 By default, historical data are kept.

**Comment by pioto** [comment]
It doesn't look like the HTML is available for modules in a Maven project, just whatever was built for the top-level module. Does this expect to work better with the `dependency-check:check` or `dependency-check:aggregate` [Maven goal](https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html)?

**Comment by Reamer** [comment]
Now also available for modules in a Maven.
