### ISSUE TITLE
Publish dependency-check-sonar-plugin on SonarQube Marketplace

### ISSUE THREAD

**Issue by jycr** [stevespringett/dependency-check-sonar-plugin#46]
Is seems that your plugin is not available on SonarQube Marketplace

Is it planned ?

Resource: 
https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace

TODO (from requirements):

- Your plugin is open-source
  - [x] Source is freely accessible
    -> https://github.com/stevespringett/dependency-check-sonar-plugin
  - [x] The license is a known FLOSS one (check the list provided by the Open Source Initiative)
    -> LGPLv3
  - [x] There's a public issue tracking system
    -> https://github.com/stevespringett/dependency-check-sonar-plugin/issues
  - [ ] Documentation is available online in English
    -> OK for quick overview : https://github.com/stevespringett/dependency-check-sonar-plugin/blob/master/README.md
    -> But no détails : https://github.com/stevespringett/dependency-check-sonar-plugin/wiki
  - [x] Binaries of each version are accessible somewhere
    -> https://bintray.com/stevespringett/owasp/dependency-check-sonar/
    -> https://github.com/stevespringett/dependency-check-sonar-plugin/releases
- Releases follow open source conventions
  - [x] A Release Candidate and feedback period are announced prior to each release. 
    -> Pre-release versions available here: https://github.com/stevespringett/dependency-check-sonar-plugin/releases
  - [ ] A "feedback period closed" notice is sent just before the release.
  - For each release the following must be available:
    - [ ] release notes that reflect all significant changes in the version
    - [x] plugin jar
      -> https://bintray.com/stevespringett/owasp/dependency-check-sonar/
      -> https://github.com/stevespringett/dependency-check-sonar-plugin/releases
- The key of your plugin should be:
  As describe https://docs.sonarqube.org/display/DEV/Build+Plugin#BuildPlugin-AdvancedBuildProperties : sonar-dependency-check-plugin -> **dependencycheck**
  - [x] short and unique
  - [x] lowercase (no camelcase)
  - [x] composed only of [a-z0-9]
  - examples: motionchart, php, scmactivity
- [x] The description of your plugin must not be misleading in terms of content (the code needs to do pretty much what the name and description say it does).
  - On initial entry into the Marketplace, SonarSource staff will test the plugin to verify reasonable functionality and quality.
  - SonarSource staff must be provided with the necessary means to do this testing without the need to sign any agreements or fill out any forms.
  - Ideally, the means to do this testing will be made available to the community at large, with the same lack of restrictions.
- [x] Your plugin does not compete with existing SonarSource products (sorry, but we gotta pay the bills somehow)
- [x] It is analysed on SonarCloud and the quality gate is green when doing a release
  -> Check: https://about.sonarcloud.io/news/2016/09/01/sonarqubedotcom-open-to-aynone.html
  -> https://sonarcloud.io/dashboard?id=org.sonarsource.owasp%3Asonar-dependency-check
- [x] It is compatible with the platform requirements (e.g. it runs on the minimum listed JRE)
- [x] your plugin must be aligned with the goal of the SonarQube platform: management of the technical debt and the quality of the code

At the end:
- [ ] Start a new thread on the [SonarQube Google Group](https://groups.google.com/forum/#!forum/sonarqube) requesting inclusion. This thread should include plugin:
> **Subject:**  [NEW PLUGIN] dependencycheck X.X.X
> **Description:** Integrates Dependency-Check reports into SonarQube
> **Home page url:** https://github.com/stevespringett/dependency-check-sonar-plugin

**Comment by stevespringett** [comment]
@jycr I have tried multiple times to get it listed, once when it was originally released when SQ was using the old Haus infrastructure, and again when using the new. 

There is too much process and rules that govern the creation and publishing of plugins. I will certainly not be asking a committee to vote every time I want to release a plugin. The whole process is nonsense and I do not want any part of it. As you can see, I have met all/most of their requirements already.

I am happy to write plugins for community consumption, but I expect the corporate entity that backs it to make it easy for the community to thrive. SonarSource does not do this.

This combined with major API changes between LTS releases and they are lucky to have the little community they do. If 7.x also has major API changes that require plugins be refactored, there will not be any future Dependency-Check SonarQube plugins from me.

**Comment by jycr** [comment]
I understand.
If you agree, I can do the "administrative steps" for you, and try to adapt the code to meet all the requirements.
Indeed, in our compagny, all needed plugins must come from marketplace. We can't install manually plugins

**Comment by stevespringett** [comment]
From my count, there are 23 plugins in the marketplace that are not developed by SonarSource or with the help of SonarSource. By comparison, there are 44 plugins recognized by SonarSource that are not included in the marketplace, including Dependency-Check. https://docs.sonarqube.org/display/PLUG/Other+Plugins

The ecosystem for community plugins not in the marketplace is larger than what's available in the marketplace. All available security-specific plugins are not available in the martketplace. This includes Checkmarx, Dependency-Check, ThreadFix, and ZAP.

There is no benefit to this project to include it.

**Comment by alixwar** [comment]
@stevespringett any news on this?
