### ISSUE TITLE
plugin don't work .... [WARNING] Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.xml

### ISSUE THREAD

**Issue by Mortagne** [stevespringett/dependency-check-sonar-plugin#47]
Hi folks,

I tried some possibility with de plugin ... and I have same issue each time.
it's impossible to view the result in Sonar.

My Configuration :
Jenkins CI - v2.73.3
Plugin : OWASP Dependency-Check Plugin - v3.0.2

SonarQube CI - v6.7(build 33306)
Plugin : Dependency-Check - v1.1.0

If I use Syntaxe Pipeline Plugin, I juste see the report in Jenkins ... nothings in SonarQube.
```
dependencyCheckAnalyzer datadir: 'dependency-check-data', hintsFile: '', includeCsvReports: false, includeHtmlReports: false, includeJsonReports: false, includeVulnReports: true, isAutoupdateDisabled: false, outdir: '', scanpath: '', skipOnScmChange: false, skipOnUpstreamChange: false, suppressionFile: '', zipExtensions: ''
                    
dependencyCheckPublisher canComputeNew: false, defaultEncoding: '', healthy: '', pattern: '', unHealthy: ''

archiveArtifacts allowEmptyArchive: true, artifacts: '**/dependency-check-report.xml', onlyIfSuccessful: true

```

if I use :
```
sh 'mvn clean package dependency-check:check'
                
withSonarQubeEnv('SonarQube-Loto') {
   // requires SonarQube Scanner for Maven 3.2+
   sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
   //sh 'mvn sonar:sonar'
}

```
i see nothing anyware.

The last sentence, are in exemple of : https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples/multi-module-maven-runner

I try to use this in DeclarativePipeline.

My DP of Jenkinsfile : 

```
#!/usr/bin/env groovy
pipeline {
    agent {
        label "master" //valeur par default
    }

    tools {
        jdk 'jdk8' //spécification du JDK
    }

    options {
        buildDiscarder(logRotator(numToKeepStr:'10'))
        timeout(time: 30, unit: 'MINUTES')
        gitLabConnection('gitlab-loto')
    }

    environment {       
        lstDistribution = "sebastien.crete@loto-quebec.com;"
    }
    stages {

        stage("Config") {
            steps {
                echo "voici le chemin du workspace"
                echo "${WORKSPACE}"
            }
        }
        
        stage("Analyse Code Quality") {            
            steps {
                echo "Static Code Analysis"
                
                sh 'mvn clean package dependency-check:check'
                
                withSonarQubeEnv('SonarQube-Loto') {
                    // requires SonarQube Scanner for Maven 3.2+
                    sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
                    //sh 'mvn sonar:sonar'
                }

            }
        }
     }

    post {
        always {
            echo "Fin de l'exécution du pipeline"
            //deleteDir()                             //Nettoyage du workspace
        }
    }    
}
```

Regards for your help.

**Comment by cwansart** [comment]
Same here. I set ` <sonar.dependencyCheck.reportPath>${project.build.directory}/dependency-check-report.xml</sonar.dependencyCheck.reportPath>` in my parent/pom.xml (a parent project of the sub projects) and still get the error message as noted by Mortagne.

Even passing it to the SonarQube Maven plugin call it shows the same message. Any solutions?

Running SonarQube 6.7.

**Comment by Vincekoe** [comment]
same here, am using SonarQube 6.7.1 LTS, It say "[WARNING] Dependency-Check report does not exist. SKIPPING", this report is generated by this plugin? does this plugin support version 6.7.1?

**Comment by bradflood** [comment]
One solution that seems to work is to add the property directly to the sonar-maven-plugin invocation

    stage ('Report') {
          withSonarQubeEnv {
        	   withMaven() {
        		mvn "sonar:sonar -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml"
         	   }
          }
    }

Jenkins 2.101
SQ 6.7
dependency-check-maven v3.1.0
dependency-check-sonar-plugin 1.1.0

I had maven property `sonar.dependencyCheck.reportPath` set in the POM, and had SonarQube configured with the default path. 
The dependency-check-sonar-plugin doesn't seem to sense either the maven property or SonarQube configuration. However, setting an environment variable on the sonar-maven-plugin did the trick

**Comment by hyh23** [comment]
Hi,everybody,could you help me to anlyze the problem?

i have installed the Dependency-Check plugin in both jenkins2.89  and sonarqube7.0.
when i start to build a project, Dependency-Check plugin seems to do not work.
by the way,the project is a test demo,can't be build.Dependency-Check plugin need build file?

i have try a lot of solutions,but it don't work.


**log:**
INFO: Sensor OWASP Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: target/dependency-check-report.xml
INFO: Process Dependency-Check report (done) | time=1ms
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.html
INFO: Sensor OWASP Dependency-Check [dependencycheck] (done) | time=4ms
INFO: Sensor jsp [findbugs]


**jenkins post step config:**
sonar.projectKey=my:demo
sonar.projectName=demo
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=.
sonar.sources=${WORKSPACE}/src
sonar.dependencyCheck.reportPath=target/dependency-check-report.xml

**Comment by stevespringett** [comment]
Why is sonar.sources specified twice?

The command-line example here 
https://github.com/stevespringett/dependency-check-sonar-plugin/blob/master/examples/command-line-project/sonar-project.properties also works with the SonarQube Runner in Jenkins.

**Comment by hyh23** [comment]
Thank you for your replay.but it doesn't work. the log is below:


INFO: Process Dependency-Check report
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: /root/.jenkins/workspace/SecPlatform/dependency-check-report.xml
INFO: Process Dependency-Check report (done) | time=2ms
WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: /root/.jenkins/workspace/SecPlatform/dependency-check-report.html
INFO: Sensor OWASP Dependency-Check [dependencycheck] (done) | time=12ms

**Comment by stevespringett** [comment]
The log differs from the properties you've specified, specifically, the target directory is missing.

If the same of the Jenkins job is SecPlatform, does dependency-check-report.xml exist in the root of the workspace? If so, your property is incorrect.

**Comment by hyh23** [comment]
I reconfigured it  as below and it works.thanks!

**jenkins post step config:**
sonar.dependencyCheck.reportPath=${WORKSPACE}/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=${WORKSPACE}/dependency-check-report.html

**LOG:**
INFO: Sensor OWASP Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Process Dependency-Check report (done) | time=129ms
INFO: Sensor OWASP Dependency-Check [dependencycheck] (done) | time=156ms

**Comment by hyh23** [comment]
Note: the sonar plug-in does not rely on a dependency scan and needs to read the configuration file after other ways of scanning.

**sonar.dependencyCheck plugin just read the report. At last ，i find that the reason.**

**Comment by kritsanut** [comment]
> Thank you for your replay.but it doesn't work. the log is below:
> 
> INFO: Process Dependency-Check report
> WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: /root/.jenkins/workspace/SecPlatform/dependency-check-report.xml
> INFO: Process Dependency-Check report (done) | time=2ms
> WARN: Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: /root/.jenkins/workspace/SecPlatform/dependency-check-report.html
> INFO: Sensor OWASP Dependency-Check [dependencycheck] (done) | time=12ms

**Hello, This command worked for me.**

`  mvn clean install org.owasp:dependency-check-maven:check sonar:sonar \
  -Dsonar.projectKey=com.myapp.org \
  -Dsonar.projectName=MyProject \
  -Dsonar.host.url=http://localhost:9000\
  -Dsonar.login=xxxxxxx \
  -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml \
  -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html`

**Comment by AbhishekMG102486** [comment]
Property 'sonar.jacoco.reportPath' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin.
Clover XML report not found
Missing property:sonar.cfn.nag.reportFiles
Missing property:sonar.checkov.reportFiles

showing......
