### ISSUE TITLE
java.lang.IllegalStateException: Unable to read plugin manifest from jar

### ISSUE THREAD

**Issue by wagoodman** [stevespringett/dependency-check-sonar-plugin#50]
After copying the 1.1.0 jar to the `extensions/plugins` dir and restarted, this is the error in the sonarqube log (and the server crashes). Maybe there is an attribute in the pom.xml missing?

**Comment by stevespringett** [comment]
What version of SonarQube are you using?

**Comment by wagoodman** [comment]
6.7

**Comment by Reamer** [comment]
Hi @wagoodman,
I tested with both version 1.1.1 and 1.1.0 of this plugin and sonarqube 6.7.5. I didn't recognize any errors.
Can you provide more informations?

**Comment by Reamer** [comment]
Please try the new version of this plugin and report a new issue if your issue is still present.
