### ISSUE TITLE
Make plugin available in Sonar Marketplace

### ISSUE THREAD

**Issue by zpavic** [stevespringett/dependency-check-sonar-plugin#53]
While the plugin can be installed manually, it would be nice if it is included in the Sonarqube marketplace.

See: https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace

This helps management of updates a bit nicer.

**Comment by rompic** [comment]
see https://github.com/stevespringett/dependency-check-sonar-plugin/issues/46
