### ISSUE TITLE
How do I get notified when a scan detects a new vulnerability

### ISSUE THREAD

**Issue by StFS** [stevespringett/dependency-check-sonar-plugin#56]
We have the following setup:

- A multi module gradle project (Java code and some Scala)
- SonarQube with dependency-check-sonar plugin and sonar-bitbucket-plugin (https://github.com/mibexsoftware/sonar-bitbucket-plugin)

The bitbucket plugin in SonarQube is set up so that it comments on our pull requests when they get created. It does a good job of commenting on code changes but when we add new vulnerable library dependencies, the bitbucket plugin does not pick up the added vulnerability and does not comment on the PR regarding that. I can confirm from the command line output that the dependency-check plugin is in fact picking up the new vulnerable library but the bitbucket plugin does not report it.

I've reported the issue on the bitbucket plugin (https://github.com/mibexsoftware/sonar-bitbucket-plugin/issues/79) but I figured I might ask here as well.

If there is some technical reason for the bitbucket plugin not being able to detect an increased number of vulnerable libraries, is there at least some way I can run the sonarqube task in gradle and get information about whether the number of vulnerable libraries has increased since the last scan?

We're trying to get this into our PR reviews but at the very least we'd like to be able to get notified on a daily basis if the number of vulnerable libraries is increasing.

**Comment by stevespringett** [comment]
I must admit, I have not used the bitbucket plugin before so I don't know what its capabilities or limitations are.

The Dependency-Check SonarQube plugin is rather simple. It simply parses dependency-check reports and creates issues in SonarQube.

From there, its up to SonarQube to provide alerting capabilities which is something I do not know if its capable of. Lots of folks use the Jenkins plugin which can fail builds or put them into a warning state. Used in combination with the email plugin, teams can get alerted whenever the build detects a new vulnerability. Not sure about SonarQubes capabilities though.

**Comment by Reamer** [comment]
Please create/modify a SonarQuality Gate. You can setup a sonar notification based on this.
