### ISSUE TITLE
Dependency Check Report doesn't display in SONAR

### ISSUE THREAD

**Issue by johnsonqu** [stevespringett/dependency-check-sonar-plugin#58]
SONAR version: 6.7
Jenkins version: 2.7.2
Dependency-Check Jenkins Plugin version: 3.1.2
Dependency-Check SONAR Plugin version: 1.1.0

I could see dependency-check-report.xml was generated successfully, but still couldn't see anything from 'Measures' tab or 'More->Dependency Check' tab as below. 
![screenshot1](https://user-images.githubusercontent.com/3131894/39235487-95b1c75c-48a8-11e8-965c-7595a88687ed.png)
![screenshot2](https://user-images.githubusercontent.com/3131894/39235488-9601b3f2-48a8-11e8-8649-122d90115e8c.png)

Your help would be highly appreciated.

**Comment by ivozzo** [comment]
Hi, we have the same problem
We're currently running: sonarqube 6.7.3 with dependency-check-sonar-plugin version 1.1.0.

As for the analysis we generate the xml and html report with dependency-check-maven and we load the report with maven sonarqube plugin

**Comment by sarvi12** [comment]
I do face same issue, I am able to generate the dependency-check-report.xml file and got it to target folder.
Updated the same target folder in Dependency Check path in Sonar Qube UI but no luck as it shows same as shown in this issue screen shot.

Sonar Qube 6.5
sonar-maven-plugin: 3.4.0.905
dep check : 3.1.2

**Comment by stevespringett** [comment]
@sarvi12 Did you look at the [examples](https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples) of how to configure Maven usage?

**Comment by sarvi12** [comment]
Thanks for your quick response, Yes. Just followed it. Worked fine, Thanks Again.

**Comment by victorfun1989** [comment]
I do fact the same issue. I use the sonar scanner with parameter -Dsonar.dependencyCheck.reportPath, but Dependency-Check report does not exist is showed in the log. I'm sure the dependency-check report exist and the reportPath is correct.

**Comment by picsouds** [comment]
just add the sonar.dependencyCheck.reportPath as a source directory.
For example in gradle ( properties["sonar.sources"] += properties["sonar.dependencyCheck.reportPath"] )

**Comment by Reamer** [comment]
With newest version the reports files doesn't need any more be part of sonar.sources. Try the new version.

**Comment by bloodzer0** [comment]
> I do face the same issue. I use the sonar scanner with parameter -Dsonar.dependencyCheck.reportPath, but Dependency-Check report does not exist is showed in the log. I'm sure the dependency-check report exist and the reportPath is correct.

hello，I have the same problem as you. How did you solve it?

**Comment by bloodzer0** [comment]
> @sarvi12 Did you look at the [examples](https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples) of how to configure Maven usage?

SonarQube Version：7.7
Sonar Scanner：3.10.0
sonar-dependency-check-plugin-1.2.3.jar：1.2.3

Wrong presentation：INFO: Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath

when i use：sonar-scanner -Dsonar.dependencyCheck.reportPath=reports/dependency-check/dependency-check-report.xml ****

**Comment by Reamer** [comment]
Hi @bloodzer0,
we have two config parameters for report paths `sonar.dependencyCheck.htmlReportPath` and `sonar.dependencyCheck.reportPath`

**Comment by bloodzer0** [comment]
> Hi @bloodzer0,
> we have two config parameters for report paths `sonar.dependencyCheck.htmlReportPath` and `sonar.dependencyCheck.reportPath`

i used：sonar-scanner -Dsonar.dependencyCheck.reportPath=/home/sonarqube/report/dependency-check-report.xml -Dsonar.dependencyCheck.htmlReportPath=/home/sonarqube/report/dependency-check-report.html

but It's the same mistake.

**Comment by bloodzer0** [comment]
> > Hi @bloodzer0,
> > we have two config parameters for report paths `sonar.dependencyCheck.htmlReportPath` and `sonar.dependencyCheck.reportPath`
> 
> i used：sonar-scanner -Dsonar.dependencyCheck.reportPath=/home/sonarqube/report/dependency-check-report.xml -Dsonar.dependencyCheck.htmlReportPath=/home/sonarqube/report/dependency-check-report.html
> 
> but It's the same mistake.

INFO: ------------- Run sensors on project
INFO: Sensor Dependency-Check [dependencycheck]
INFO: Process Dependency-Check report
INFO: Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.reportPath:/home/sonarqube/report/dependency-check-report.xml
INFO: Analysis skipped/aborted due to missing report file
INFO: Dependency-Check HTML report does not exists. Please check property sonar.dependencyCheck.htmlReportPath:/home/sonarqube/report/dependency-check-report.html
INFO: HTML-Dependency-Check report does not exist.
INFO: Process Dependency-Check report (done) | time=4ms
INFO: Sensor Dependency-Check [dependencycheck] (done) | time=4ms
INFO: Sensor Zero Coverage Sensor

**Comment by Reamer** [comment]
This plugin **doesn't** create the report files. To you use [DependencyCheck](https://github.com/jeremylong/DependencyCheck)?

**Comment by bloodzer0** [comment]
> This plugin **doesn't** create the report files. To you use [DependencyCheck](https://github.com/jeremylong/DependencyCheck)?

OK thank you！

**Comment by Reamer** [comment]
This plugin will always give you the full path if a file is not found. You should always configure the path correctly. Check on your Jenkins if the path is also correct. I would not use environment variables, specify a relative path instead.
