### ISSUE TITLE
How does it work with preview analysis

### ISSUE THREAD

**Issue by amimas** [stevespringett/dependency-check-sonar-plugin#67]
Hello,

I use preview analysis for all the branch builds and regular analysis for the master branch. The preview analysis using Gradle based scanner combined with another plugin installed in sonarqube server allows automatically posting comments at the commit level if any issues are found. This helps during code review and helps prevent unwanted issues from getting meged.

How does this plugin work with sonarqube's preview analysis? Maybe this is a question for sonarqube scanner but not sure...

**Comment by stevespringett** [comment]
This would certainly be a question for SQ. This plugin simply reads in a dependency-check XML report and for every non-suppressed vulnerability in the report, creates issues (at the project level) in SQ. From there, it's up to SQ to figure out what to do with it, visualize it, etc. But its important to note that the issues created from this plugin are assigned to the SQ project, not an individual source file.

**Comment by Reamer** [comment]
The preview feature is deprecated from sonarqube. Take a look into https://groups.google.com/forum/#!topic/sonarqube/4bzwxkqJGAc
Because of that I close this issue
