### ISSUE TITLE
Unable to disable severity mapping?

### ISSUE THREAD

**Issue by tracyzhuyq** [stevespringett/dependency-check-sonar-plugin#68]
I used -1 for severity like below, but the severity is still enabled. How can all severity disabled?
<sonar.dependencyCheck.severity.critical>-1</sonar.dependencyCheck.severity.critical>
<sonar.dependencyCheck.severity.major>-1</sonar.dependencyCheck.severity.major>

**Comment by Reamer** [comment]
An issue must have an severity. It's not possible to disable severity mapping.
Check out the configuration options
```
sonar.dependencyCheck.severity.blocker
sonar.dependencyCheck.severity.critical
sonar.dependencyCheck.severity.major
sonar.dependencyCheck.severity.minor
```
If you set all options to "-1" the severity is INFO.
