### ISSUE TITLE
Is there a way to skip parsing the reports?

### ISSUE THREAD

**Issue by renedupont** [stevespringett/dependency-check-sonar-plugin#69]
Hello,

**We have the following setup:**
We are using one Sonarqube server instance for a bunch of different kind of projects (some are java, some python, skala, etc.). We also installed this dependency-check-sonar-plugin that picks up the reports in a defined sonarqube jenkins pipeline stage. 

**Our issue is:**
Now, there are some project types where we don't want to do the dependency-check (e.g. because there is no analyzer for the language used in that project) BUT still want Sonarqube to do its regular scanning job on it. 
Since this plugin is installed, Sonarqube tries to pick up reports on these projects but won't find any because we didn't do the dependency-check on this specific project and will finally throw an error
`throw new FileNotFoundException("Dependency-Check report does not exist.");`

Is there a way, to let the plugin know that it should skip this specific project? Or any other idea regarding this? A property in the sonar project properties file to control this would be nice, or is anything speaking against this?

_Thanks_

**Comment by Reamer** [comment]
I change the plugin output. https://github.com/stevespringett/dependency-check-sonar-plugin/commit/8738936ab2a36434de6e796e35e6a6bb5360ab71
We can not disable the plugin, but we are know "skipping" this plugin if no report files are found.

**Comment by Reamer** [comment]
With no reports I get this output now
```
[INFO] Sensor Dependency-Check [dependencycheck]
[INFO] Process Dependency-Check report
[INFO] Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ...../target/dependency-check/dependency-check-report.xml
[INFO] Analysis skipped/aborted due to missing report file
[INFO] Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.htmlReportPath: ...../target/dependency-check/dependency-check-report.html
[INFO] Process Dependency-Check report (done) | time=6ms
```
