### ISSUE TITLE
Improve README.md to clearly state that plugin only uploads XML/HTML reports and does not create them

### ISSUE THREAD

**Issue by marcin-chwedczuk** [stevespringett/dependency-check-sonar-plugin#70]
Today at my workplace I successfully configured dependency check plugin on our SonarQube instance. First thank you for writing this plugin, it helped us a lot. 

Now I have a few suggestions:

*  README.md does not states clearly that this plugin only gathers generated reports and does not performs scanning itself (there is only one sentence about it and hidden in the middle of the text)
* I would appreciate if there was a short section describing how to download OWASP dependency checker (command line version) and how to run it to generate XML/HTML reports. I am writing this because I was configuring this plugin for .NET project and as far as I remember there were only plugins for Maven/Ant; nothing for MSBuild which .NET uses.

I think adding this info would help people to setup this plugin more quickly.

**Comment by stevespringett** [comment]
Documentation on setting up Dependency-Check is in the Dependency-Check repo at: 
https://jeremylong.github.io/DependencyCheck/
This covers Ant, Maven, and CLI installation, configuration, and execution. I'll make a note to update the readme to point to their docs.

The CLI example in this repo should have hopefully provided you a simple way to get started.
https://github.com/stevespringett/dependency-check-sonar-plugin/tree/master/examples/command-line-project
