### ISSUE TITLE
Issue tracker problem

### ISSUE THREAD

**Issue by elrond30** [stevespringett/dependency-check-sonar-plugin#72]
Hello,
Recentlly I updated the Dependency-Check plugin for Jenkins. The sonar plugin I can't update, because I have SonarQube 5.6.6. The sonar plugin is in version 1.0.3.
Since the update of the Jenkins Plugin I started to have a problem with the evidences in SonarQube. The evidences that I marked as false positive in a previous scan, are now as a positive vulnerability again. The coments of the evidences also cahnges.
The problems seems to be a problem identifying each evidences.

**Comment by stevespringett** [comment]
Similar issues were reported in SQ6 and have been fixed in the most recent version of the plugin.

Possibly related to #55 and fixed in #61.

Feel free to attempt to backport to see if that solves the issue or not.

**Comment by Reamer** [comment]
Sonarqube 5.6 is not supported by this plugin. Close this issue in favour of #55
