### ISSUE TITLE
Missing information in sonarq measures

### ISSUE THREAD

**Issue by razeitona** [stevespringett/dependency-check-sonar-plugin#73]
Hi,

I've TeamCity integrated with SonarQ 6.7, where TeamCity runs dependency check, generates the report and set properties to the SonarQ reportPath (both XML and HTML)

In SonarQ I can see the HTML report (in More > Dependency-Check menu option)
However in measures option I can only see the total dependencies

![image](https://user-images.githubusercontent.com/10911333/44786552-cac1ad00-ab94-11e8-9467-35efc5d3ea50.png)

In TeamCity SonarQ build step I'm setting the paths as,
```
/d:"sonar.dependencyCheck.htmlReportPath=C:\tools\dependency-check\log\dependency-check-report.html" 
/d:"sonar.dependencyCheck.reportPath=C:\tools\dependency-check\log\dependency-check-report.xml"
```

**Comment by razeitona** [comment]
Other doubt,

Sonar dependency check plugin, in TeamCity at least, can only be configured in General Settings. And not project by project.

If we set the dependencyCheck report path and html report path isn't going to override reports everytime a project does a report?

_**Update:**_
The error that is being generated is 
"WARNING: WARN: skipping dependency '....' as no inputFile could established."

**Comment by razeitona** [comment]
@stevespringett Do you know what can be related with?
Why when reading the file for total dependnecies is different from reading the other properties?
The error is in "WARNING: WARN: skipping dependency 'System.Data.Common.dll' as no inputFile could established." 

To which folder is he getting? 
Team City Agent and sonarqube filesystem base and working dir
[10:48:58][Step 6/6] INFO: Base dir: D:\BuildAgent\work\9734750dea92d66d\src\[ProjectName]
[10:48:58][Step 6/6] INFO: Working dir: D:\BuildAgent\work\9734750dea92d66d\.sonarqube\out\.sonar\[projectname]_3107A353-93F9-4269-B054-F533FB5E45B2

Report Path 
D:\BuildAgent\work\9734750dea92d66d\[report-file]

**Comment by fr33ky** [comment]
We actually have the same problem here running:
* jenkins (2.121.3)
* sonar (6.7.4)
* dependency check sonar plugin (1.1.1)
* dependency check CLI (3.3.1)

We properly generate dependency check report via CLI and then provide them to sonar.
HTML report is available in Sonar
Only Total dependencies is properly displayed. I then guess the XML report is properly analysed.

**Comment by fr33ky** [comment]
I reverted `f5a1775`, which workarounds #55, but introduced a check on report file as an `InputFile` , and we now have properly reported values, vulnerabilites, etc.
I hope this will help.

**Comment by razeitona** [comment]
And when clicking in the High Vulnerability or any other measure under "OWASP Dependency-Check" you get results? I have just the number and an info of "No Results"

I've set the path of dependency check report to be in "src\[module name]" and add the report to be in inclusions as "**\dependency-check-report.xml" and got some results

the [module name] is the root folder of the bin folder that you are checking

**Comment by fr33ky** [comment]
> And when clicking in the High Vulnerability or any other measure under "OWASP Dependency-Check" you get results? I have just the number and an info of "No Results"

![OWASP-Dependency-Check](https://user-images.githubusercontent.com/38321094/45115967-ba3fa280-b151-11e8-9f04-3fa51382eaa1.png)
Yes, I have, but I had to revert the above mentioned commit, which requires, as far as I understand, `dependency-check-report.xml` to be considered as a source file.
This is then the reason why you got some results when adding the report in the inclusions.

I understand #55 (which is then back when I revert f5a1775)…
reverting… or adding report as a source file… or another solution… I guess will have to wait for the author.

**Comment by razeitona** [comment]
But you have results here?
![image](https://user-images.githubusercontent.com/10911333/45140565-77aeb200-b1b3-11e8-8017-e9a159ce88b4.png)

**Comment by fr33ky** [comment]
Ho, I missed this one. So, here, I don't (as there is no real file to be listed here).
Nevertheless there are listed in the SQ Issues tab, as critical, major or minor, depending on their criticity, and as Issue type = vulnerabilities.

**Comment by fr33ky** [comment]
I generate HTML report too, which is properly displayed within the "More > Dependency-Check" tab.

**Comment by razeitona** [comment]
Download the source from the commit you said
https://github.com/stevespringett/dependency-check-sonar-plugin/tree/f5a1775186743ccafaafb54775469fd8c176d995

But didn't worked, needed to make some changes

**Comment by srudolph-credera** [comment]
I just ran into the same issue and was able to resolve it without modifying the plugin's source code:  the report XML file needs to be inside a path defined by the `sonar.sources` property and so I created a `reports` folder, told Dependency Check to place its reports there, and added it to my `sonar.sources`.

**Comment by Reamer** [comment]
Please upgrade to newest version 1.2.0 (for Sonarqube 7.3 and above) or 1.1.2 (for Sonarqube 6.7.5 and above)
