### ISSUE TITLE
SonarQube 7.3 Compatibility

### ISSUE THREAD

**Issue by lulog1** [stevespringett/dependency-check-sonar-plugin#74]
Please ensure that this plugin is compatible with SonarQube 7.3, which has been released publicly.

See also issue #66 (SonarQube 7.2 compatibility).

**Comment by pethers** [comment]
Basic functionality works. runs 7.3 now https://www.hack23.com/sonar/component_measures?id=com.hack23.cia%3Acia-all&metric=total_dependencies . 

Problem with https://www.hack23.com/sonar/project/extension/dependencycheck/report?id=com.hack23.cia%3Acia-all&qualifier=TRK , but do not generate html report probably why.

**Comment by pethers** [comment]
https://www.hack23.com/sonar/project/extension/dependencycheck/report?id=com.hack23.cia%3Acia-all&qualifier=TRK works now when I generate html report and set property.

**Comment by znerd** [comment]
Perhaps #66 and #60 can then also be closed? They related to SonarQube 7.2 and 7.1 respectively.
