### ISSUE TITLE
Project specific setting does not override global one.

### ISSUE THREAD

**Issue by remy-tiitre** [stevespringett/dependency-check-sonar-plugin#80]
I use Gradle and in rootProject I have
sonarqube {
    properties {
        property 'sonar.dependencyCheck.reportPath', "${buildDir}/reports/dependency-check-report.xml"
    }
}

Dependency Check Sonar Plugin does find my report but it seems that the property is not overrideing the global value (set inside Sonar UI). This will lead to a warning:
Dependency-Check report does not exist. SKIPPING. Please check property sonar.dependencyCheck.reportPath: ${WORKSPACE}/dependency-check-report.html

I'm not using Maven, so no wonder that ${WORKSPACE} is not resolved. I first thought that I should enter empty value in Sonar UI and always require this property to be set at project level but UI does not allow empty values there.

**Comment by Reamer** [comment]
@remy-tiitre Can you please try the [plugin version 1.1.0](https://github.com/stevespringett/dependency-check-sonar-plugin/releases/tag/1.1.0). Maybe it's related to #82

**Comment by Reamer** [comment]
Can you provide an example project?

**Comment by remy-tiitre** [comment]
What do you mean? Gradle project? Its a little bit complicated, as we are using custom gradle wrapper and it has some internal logic in it that can't be shared. But I don't think it has anything to do with the project configuration. LIke I wrote in the first post it seems that settings provided at the gradle project level do not override global settings entered in Sonarqube UI (Administration > Configuration > Dependency-Check. Both of them are used. So yes, Sonar will find my xml and html reports but it will also give me a warning that it can't find any reports from the path that has been entered in UI.

**Comment by Reamer** [comment]
Tested gradle with this example project and it works as expected. https://github.com/stevespringett/dependency-check-sonar-plugin/commit/ebd1b99f56f44a94f89cac0f1822415245cd1bc1
