### ISSUE TITLE
add tag owasp-a9 to KnownCveRuleDefinition will correct security_reports

### ISSUE THREAD

**Issue by pethers** [stevespringett/dependency-check-sonar-plugin#83]
currently in security reports issues get displayed as Not OWASP instead of as A9 - Using Components with Known Vulnerabilities 

example at https://www.hack23.com/sonar/project/security_reports/owasp_top_10?id=com.hack23.cia%3Acia-all

**Comment by Reamer** [comment]
How you get the "Security Report"-Tab in your project? This tab is not displayed in my projects.
