### ISSUE TITLE
Dependency-Check report does not exist in TypeScript

### ISSUE THREAD

**Issue by naithagoni** [stevespringett/dependency-check-sonar-plugin#86]
I am new to SonarQube. Somehow I can see some bugs, code smells etc., except vulnerabilities.
I have installed "dependency-ckeck-sonar-plugin" in SonarQube and got the error "Dependency-Check report does not exist.". This also shows 0 vulnerabilities.

**sonar-project.properties**

sonar.host.url=http://localhost:9000
sonar.projectKey=jest-sonar-reporter
sonar.projectName=applauncher-web
sonar.description=Angular SPA Frontend
sonar.verbose=true
sonar.projectVersion=7.3
sonar.sources=src/app
sonar.exclusions=**/node_modules/**,**/dev/**,**/*.js,**/*.vb,**/*.css,**/*.scss
sonar.tests=src/app
sonar.test.inclusions=**/*.unit.spec.ts
sonar.sourceEncoding=UTF-8
sonar.dependencyCheck.reportPath=reports/dependency-check-report.xml
sonar.testExecutionReportPaths=reports/test-reporter.xml
sonar.genericcoverage.unitTestReportPaths=reports/test-reporter.xml

Note: I am using Angular6, TypeScript, and nodejs
any help please..
![screenshot from 2018-11-01 16-52-52](https://user-images.githubusercontent.com/11850500/47865833-8f926300-ddfd-11e8-8775-09d5455a18d6.png)

**Comment by Reamer** [comment]
Hi @naithagoni ,
have you created the [dependency report](https://www.owasp.org/index.php/OWASP_Dependency_Check) in xml format before running sonar?
I advise you to use the master branch version of this plugin till your next release, because of #82

**Comment by Reamer** [comment]
I checked the official Homepage. https://www.owasp.org/index.php/OWASP_Dependency_Check or https://jeremylong.github.io/DependencyCheck/
At the moment there is not support for Angular or Typescript.
