### ISSUE TITLE
HTML Report is showing, but nothing appearing under 'Measures'

### ISSUE THREAD

**Issue by shanekelly-bbc** [stevespringett/dependency-check-sonar-plugin#87]
Hi Steve, thanks for creating and supporting this plugin.

We are currently triggering OWASP Dependency Checker via maven running as part of a Jenkins job. The Sonarqube page for that project finds the html report (and the xml report, judging by the logs); we can see it under the 'More/Owasp Dependency-Check' tab in the project overview, and we can see that there are several vulnerabilities in our dependencies.

However, under 'Measures/Owasp Dependency-Check', while it states that there are 149 dependencies (is seeing the report, I guess), non of the vulnerabilities are showing -everything is '0'. We're wondering why this might be? I have specified low values for the various threat categories, both in the UI and in the maven job:

```
org.owasp:dependency-check-maven:check
-Dformat=all
org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar
-Dsonar.host.url=https://oursever/sonar
-Dsonar.scm.disabled=true
-Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
-Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html
-Dsonar.dependencyCheck.severity.critical=4.0
-Dsonar.dependencyCheck.severity.major=2.0
-Dsonar.dependencyCheck.severity.minor=0.0
```

Please bear in mind currently integrating version 1.1.1 of your plugin with a 7.1.0.11001 Sonarqube server; so this may be an imcompatibility issue, given that 1.1.1 is for version 7.3 and above -however I have tried with version 1.1.0 and the same issue is present.

Thank you for looking at this, and for any advice or support you can give.

Shane

**Comment by Reamer** [comment]
Hi @shanekelly-bbc ,
in next days I want release a new version. You can try the newest version when building the branch [SonarQube_6.x](https://github.com/stevespringett/dependency-check-sonar-plugin/tree/SonarQube_6.x). master branch is for sonarqube 7.3+

I updated the example project a minute ago and see measures
![screenshot_2018-11-05 measures - single module maven example](https://user-images.githubusercontent.com/454320/48023358-dbb30f80-e13d-11e8-99f4-c8e4f4572475.png)

Best Regards
Reamer

**Comment by shanekelly-bbc** [comment]
Thank you Reamer, this solved our problem!
