### ISSUE TITLE
Switch off Dependency-Check analysis in Sonarqube for individual projects

### ISSUE THREAD

**Issue by cpydevelop** [stevespringett/dependency-check-sonar-plugin#88]
We use Sonarqube to check Pull Request.And in Jenkins logs we have java error.io.FileNotFoundException: Dependency-Check report does not exist. Indeed, we do not use the dependency-check-maven plugin in our project and this report file is not really formed.How to disable Dependency-Check analysis in Sonarqube for individual projects?
This is list of options, which we use for analyse.
-Dsonar.projectKey="my_project.key"
-Dsonar.projectKey="my_project.key"/<target>
-Dsonar.dependencyCheck.reportPath=${WORKSPACE}/dependency-check-report.xml
-Dsonar.dependencyCheck.htmlReportPath=${WORKSPACE}/dependency-check-report.html
-Dsonar.skip=false</targets>

**Comment by Reamer** [comment]
Disabling is not possible, only skipping. Skipping is at the moment not implemented.

**Comment by Reamer** [comment]
Closing in favour of #69
