### ISSUE TITLE
[ERROR] api.nodesecurity.io

### ISSUE THREAD

**Issue by bartvde** [stevespringett/dependency-check-sonar-plugin#94]
Currently the SonarQube runs fail for us with:

```
[INFO] Analysis Complete (5 seconds)

[ERROR] api.nodesecurity.io

[ERROR] api.nodesecurity.io
```

How can we switch to the new way (https://stackoverflow.com/questions/53716991/node-security-service-shutdown-getaddrinfo-enotfound-api-nodesecurity-io) ?

**Comment by Reamer** [comment]
Why you think, that this error comes from this plugin?

**Comment by bartvde** [comment]
Good question, I am actually not sure. I only know it's coming from SonarQube and this plugin is running the OWASP reports, but it could also arise from somewhere else

**Comment by bartvde** [comment]
sorry about that @Reamer the project is unfortunately private, will try to figure out where that error is coming from

Thanks for your help so far.
